### ISSUE TITLE
about adding classes

### ISSUE THREAD

**Issue by zhukaii** [brjathu/iTAML#9]
The function 'add_classes' in basic_net.py is not called in the code, so is the number of final classification nodes(10 or 100) of the network fixed? Is there any other place in the code where the number of nodes(classifier) increases？Thanks!

**Comment by brjathu** [comment]
Hi @zhukaii , yes we do not add new neurons to the model in the process, we simply had 100 neurons at the last layer, and train the model, however, this is same as adding new neurons, since the gradients are calculated for each task separately. You can still call add_classes, functions, it would be the same!

**Comment by zhukaii** [comment]
Thank you！
